<?php

namespace BGKT\AdminBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEmails()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.email FROM BGKTAdminBundle:User u  '
            )
            ->getResult();
    }

    public function findEmail()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.email FROM BGKTAdminBundle:User u WHERE u.id = 6 '
            )
            ->getResult();
    }


    public function findByRole()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.role FROM BGKTAdminBundle:User'
            )
            ->getResult();
    }
}
