<?php

namespace BGKT\AdminBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEmails()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.email FROM BGKTAdminBundle:User u  '
            )
            ->getResult();
    }

    public function findEmail()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.email FROM BGKTAdminBundle:User u WHERE u.id = 6 '
            )
            ->getResult();
    }


    public function findByRole()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.role FROM BGKTAdminBundle:User'
            )
            ->getResult();
    }

    /**
     * Retourne un objet queryBuilder (utilisé dans le formulaire DevoirType)
     * La requête permet de retourner tous les users ayant pour role : ROLE_TEACHER
     * @param $role
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findByRoles($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('BGKTAdminBundle:User', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%' . $role . '%');
        return $qb;
    }
}
