# Route des fonctionnalités pour les utilisateurs (Professeurs ou étudiants)

# Accueil
user_homepage:
    path: /homepage
    defaults : { _controller: BGKTAdminBundle:Auth:indexUser}

# Cours CRUD :

#Create
user_ajouter_cours:
    path: /cours/ajouter
    defaults : { _controller: BGKTCoreBundle:Cours:new}

#Read
user_liste_cours:
    path: /cours/liste
    defaults : { _controller: BGKTCoreBundle:Cours:display}

#Update
user_modifier_cours:
    path: /cours/modifier/{id}
    defaults : { _controller: BGKTCoreBundle:Cours:edit}

#Delete
user_supprimer_cours:
    path: /cours/supprimer/{id}
    defaults : { _controller: BGKTCoreBundle:Cours:delete}


# Devoir CRUD

#Create
user_ajouter_devoir:
    path: /devoir/ajouter
    defaults: { _controller: BGKTCoreBundle:Devoir:new}

#Read
user_liste_devoir:
    path: /devoir/liste
    defaults: { _controller: BGKTCoreBundle:Devoir:display}

#Update
user_modifier_devoir:
    path: /devoir/modifier/{id}
    defaults: { _controller: BGKTCoreBundle:Devoir:edit}

#Delete
user_supprimer_devoir:
    path: /devoir/supprimer/{id}
    defaults: { _controller: BGKTCoreBundle:Devoir:delete}


#route vers le calendrier de l'utilisateur
user_calendarPage:
    path: /userCalendarPage
    defaults:
        _controller: BGKTCoreBundle:Epi:userCalendarShow


# Route Authentification

# Login / Logout
login:
    path: /login
    defaults:
        _controller: BGKTAdminBundle:Auth:login

login_check:
    path: /login_check

logout:
    path: /logout

default_security_target:
    path: /login

# Mot de passe
forgot_password:
    path: /forgotpassword
    defaults:
        _controller: BGKTAdminBundle:Auth:forgotPassword


check_forgot_password:
    path: /forgotpassword/{email}/{cle}
    defaults:
        _controller: BGKTAdminBundle:Auth:checkForgotPassword

#admin - back end => interface d'administration
abo_admin:
   resource: "@BGKTAdminBundle/Resources/config/routing.yml"
   prefix: /admin/users/





   