# route qui gère l'upload en lui même en asynchone
ajax_snippet_image_send:
    path: /ajax/snippet/image/send
    defaults:
        _controller: BGKTCoreBundle:Epi:ajaxSnippetImageSend

## Routes vers les différentes pages de l'utilisateur

#route vers le calendrier de l'utilisateur
user_calendarPage:
    path: /userCalendarPage
    defaults:
        _controller: BGKTCoreBundle:Epi:userCalendarShow

#route pour l'upload des cours
user_uploadpage:
    path: /userUploadPage
    defaults:
        _controller: BGKTCoreBundle:Epi:uploadDocumentView

# Route pour l'upload de TD
user_uploadpageTD:
    path: /userUploadPageTD
    defaults:
        _controller: BGKTCoreBundle:Epi:uploadDocumentTDView

# Route des fonctionnalités pour les utilisateurs (Professeurs ou étudiants)

# accueil
user_homepage:
    path: /homepage
    defaults : { _controller: BGKTAdminBundle:Auth:indexUser}

# Cours CRUD :

#Create
user_ajouter_cours:
    path: /cours/ajouter
    defaults : { _controller: BGKTCoreBundle:Cours:new}

#Read
user_liste_cours:
    path: /cours/liste
    defaults : { _controller: BGKTCoreBundle:Cours:display}

#Update
user_modifier_cours:
    path: /cours/modifier/{id}
    defaults : { _controller: BGKTCoreBundle:Cours:edit}

#Delete
user_supprimer_cours:
    path: /cours/supprimer/{id}
    defaults : { _controller: BGKTCoreBundle:Cours:delete}


# Devoir CRUD

#Create
user_ajouter_devoir:
    path: /devoir/ajouter
    defaults: { _controller: BGKTCoreBundle:Devoir:new}

#Read
user_liste_devoir:
    path: /devoir/liste
    defaults: { _controller: BGKTCoreBundle:Devoir:display}

#Delete
user_supprimer_devoir:
    path: /devoir/supprimer/{id}
    defaults: { _controller: BGKTCoreBundle:Devoir:delete}

#login
login:
    path: /login
    defaults:
        _controller: BGKTAdminBundle:Auth:login


login_check:
    path: /login_check

logout:
    path: /logout

forgot_password:
    path: /forgotpassword
    defaults:
        _controller: BGKTAdminBundle:Auth:forgotPassword


check_forgot_password:
    path: /forgotpassword/{email}/{cle}
    defaults:
        _controller: BGKTAdminBundle:Auth:checkForgotPassword

default_security_target:
    path: /login



#admin - back end => interface d'administration
abo_admin:
   resource: "@BGKTAdminBundle/Resources/config/routing.yml"
   prefix: /admin/users/





   