# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true

    app.twig_extension:
        class: BGKT\CoreBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension}

    twig_extension:
        class: BGKT\CoreBundle\Twig\RawFilterExtension
        public: false
        tags:
            - { name: twig.extension }

#
#    BGKT\CoreBundle\Service\FileUploader:
#        arguments:
#            $targetDirectory: '%cours_directory%'

    BGKT\CoreBundle\EventListener\CoursUploadLoadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
