<?php

namespace BGKT\CoreBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function findAllByDepositaire($nomDepositaire){
        return $this->getEntityManager()
            ->createQuery('
            SELECT c
            FROM BGKTCoreBundle:Cours c
            WHERE c.nomDepositaire = :nomDepositaire')
            ->setParameter('nomDepositaire', $nomDepositaire)
            ->getResult();
    }
}
