<?php

namespace BGKT\CoreBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    /**
     * Retrouve toutes les occurences des cours pour un professeur
     * @param $profId
     * @return array
     */
    public function findAllByProfesseur($profId){
        return $this->getEntityManager()
            ->createQuery('
            SELECT c
            FROM BGKTCoreBundle:Cours c
            WHERE c.user = :id')
            ->setParameter('id', $profId)
            ->getResult();
    }
}
