<?php

namespace BGKT\CoreBundle\Repository;

/**
 * DevoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevoirRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function findAllByDepositaire($nomDepositaire){
        return $this->getEntityManager()
            ->createQuery('
            SELECT d
            FROM BGKTCoreBundle:Devoir d
            WHERE d.nomDepositaire = :nomDepositaire')
            ->setParameter('nomDepositaire', $nomDepositaire)
            ->getResult();
    }
}
