<?php

namespace BGKT\CoreBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

}
