services:
#    abo_core.example:
#        class: BGKT\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    core.file_uploader:
         class: BGKT\CoreBundle\Service\FileUploader
         arguments:
              - '%cours_directory%'
              - '%devoir_directory%'
#            $targetDirectory: '%cours_directory%'

