<?php

namespace BGKT\CoreBundle\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;
use BGKT\CoreBundle\Entity\Cours;
use BGKT\CoreBundle\Form\CoursType;
use  BGKT\CoreBundle\Service\FileUploader;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class CoursController extends Controller
{

    /**
     * @Route("/cours/ajouter", name="user_ajouter_cours")
     */
    public function newAction(Request $request)
    {
        $cours = new Cours();
        $form = $this->createForm(CoursType::class, $cours);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

//            $file = $cours->getDocument();
            $cours=$this->get('core.file_uploader')->upload($cours);
            $em = $this->getDoctrine()->getManager();
            $em->persist($cours);
            $em->flush();


            //            $file = $cours->getDocument();
//            $fileName = $this->get('core.file_uploader')->upload($file);
//            $cours->setDocument($fileName);

            // ... persist the $cours variable or any other work
//
            return $this->redirect($this->generateUrl('core_liste_cours'));

//            return $this->render('BGKTCoreBundle:cours:listeCours.html.twig', array('lstCours' => $lstCours));
        }

        return $this->render('BGKTCoreBundle:cours:ajouterCours.html.twig', array(
            'form' => $form->createView(),
        ));
    }


//    public function editAction(Request $request, ProfileModel $profileModel)
//    {
//        $cours->setDocument(
//            new File($this->getParameter('cours_directory') . '/' . $cours->getDocument())
//        );
//    }


    public function displayAction()
    {
        $lstCours = $this->getDoctrine()->getManager()->getRepository('BGKTCoreBundle:Cours')->findAll();
        return $this->render('BGKTCoreBundle:cours:listeCours.html.twig', array('lstCours' => $lstCours));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
